#!/bin/bash
#! /bin/bash
clear
replace="$1"
replace_with="$2"
echo replacing $replace
echo with $replace_with
containing_directory_path="./"
file_list=$(find ./ -name "*.c" -o -name "*.h")
for file in $file_list
do
echo $file
sed -i -- "s/$replace/$replace_with/g" $file
done